# Build validation workflow for Next.js app with pnpm
#
# This workflow checks if the Next.js application builds successfully
#
name: Build Validation

on:
  # Runs on pushes targeting any branch
  push:
    branches: ["**"]

  # Runs on pull requests targeting any branch
  pull_request:
    branches: ["**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Cancel in-progress workflows when a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # Uses packageManager field from package.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Run type checking and linting
        run: pnpm check

      - name: Run i18n translation validation
        run: |
          echo "🌐 Validating translation files..."
          pnpm i18n:check --locales messages --source en --format next-intl --unused src
